# Generated by Django 4.2 on 2024-09-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
