# Generated by Django 4.2 on 2024-09-29 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_alter_survey_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='YesNoQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('question_type', models.CharField(choices=[('yes_no', 'Yes/No'), ('multiple_choice', 'Multiple Choice'), ('matrix', 'Matrix'), ('ranking', 'Ranking')], max_length=50)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_questions', to='dashboard.survey')),
            ],
            options={
                'unique_together': {('survey', 'order', 'text')},
            },
        ),
        migrations.CreateModel(
            name='RankingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('question_type', models.CharField(choices=[('yes_no', 'Yes/No'), ('multiple_choice', 'Multiple Choice'), ('matrix', 'Matrix'), ('ranking', 'Ranking')], max_length=50)),
                ('options', models.JSONField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_questions', to='dashboard.survey')),
            ],
            options={
                'unique_together': {('survey', 'order', 'text')},
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('question_type', models.CharField(choices=[('yes_no', 'Yes/No'), ('multiple_choice', 'Multiple Choice'), ('matrix', 'Matrix'), ('ranking', 'Ranking')], max_length=50)),
                ('options', models.JSONField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_questions', to='dashboard.survey')),
            ],
            options={
                'unique_together': {('survey', 'order', 'text')},
            },
        ),
        migrations.CreateModel(
            name='MatrixQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('question_type', models.CharField(choices=[('yes_no', 'Yes/No'), ('multiple_choice', 'Multiple Choice'), ('matrix', 'Matrix'), ('ranking', 'Ranking')], max_length=50)),
                ('rows', models.JSONField()),
                ('columns', models.JSONField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_questions', to='dashboard.survey')),
            ],
            options={
                'unique_together': {('survey', 'order', 'text')},
            },
        ),
    ]
