# Generated by Django 4.2 on 2024-09-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixquestion',
            name='question_type',
            field=models.CharField(choices=[('YesNoQuestion', 'Yes/No'), ('MultipleChoiceQuestion', 'Multiple Choice'), ('MatrixQuestion', 'Matrix'), ('RankingQuestion', 'Ranking')], max_length=50),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='question_type',
            field=models.CharField(choices=[('YesNoQuestion', 'Yes/No'), ('MultipleChoiceQuestion', 'Multiple Choice'), ('MatrixQuestion', 'Matrix'), ('RankingQuestion', 'Ranking')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rankingquestion',
            name='question_type',
            field=models.CharField(choices=[('YesNoQuestion', 'Yes/No'), ('MultipleChoiceQuestion', 'Multiple Choice'), ('MatrixQuestion', 'Matrix'), ('RankingQuestion', 'Ranking')], max_length=50),
        ),
        migrations.AlterField(
            model_name='yesnoquestion',
            name='question_type',
            field=models.CharField(choices=[('YesNoQuestion', 'Yes/No'), ('MultipleChoiceQuestion', 'Multiple Choice'), ('MatrixQuestion', 'Matrix'), ('RankingQuestion', 'Ranking')], max_length=50),
        ),
    ]
