# Generated by Django 4.2 on 2024-09-30 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_studio', '0002_alter_matrixquestion_question_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrixquestion',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='rankingquestion',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='yesnoquestion',
            name='question_type',
        ),
    ]
