# Generated by Django 4.2 on 2024-09-30 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0002_alter_survey_expires_at'),
        ('survey_studio', '0002_alter_matrixquestion_question_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField()),
                ('last_question_id', models.PositiveIntegerField(blank=True, null=True)),
                ('last_question_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.survey')),
            ],
        ),
        migrations.CreateModel(
            name='YesNoAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yes_no_answers', to='survey_studio.yesnoquestion')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_answers', to='survey_respondent.respondent')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_survey_answers', to='dashboard.survey')),
            ],
            options={
                'unique_together': {('respondent', 'question')},
            },
        ),
        migrations.CreateModel(
            name='RankingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ranking', models.JSONField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_answers', to='survey_studio.rankingquestion')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_answers', to='survey_respondent.respondent')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_survey_answers', to='dashboard.survey')),
            ],
            options={
                'unique_together': {('respondent', 'question')},
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_option', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_answers', to='survey_studio.multiplechoicequestion')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_answers', to='survey_respondent.respondent')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_survey_answers', to='dashboard.survey')),
            ],
            options={
                'unique_together': {('respondent', 'question')},
            },
        ),
        migrations.CreateModel(
            name='MatrixAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer_matrix', models.JSONField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_answers', to='survey_studio.matrixquestion')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_answers', to='survey_respondent.respondent')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_survey_answers', to='dashboard.survey')),
            ],
            options={
                'unique_together': {('respondent', 'question')},
            },
        ),
    ]
