# Generated by Django 4.2 on 2024-09-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_respondent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondent',
            name='last_question_id',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='last_question_type',
        ),
        migrations.AddField(
            model_name='respondent',
            name='last_question_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
